server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password123

rabbitmq:
  queue:
    notification: notification.queue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true