server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Use file: prefix WITHOUT // for absolute paths on Mac
          search-locations: file:/Volumes/Crucial X9/Vishal/java/Task-manager-platform/config-server/src/main/resources/shared-configs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/